title: The OpenMetrics project — Creating a standard for exposing metrics data
baseurl: https://openmetrics.io
languagecode: en
disableKinds: [taxonomy, taxonomyTerm]

params:
  description: |
    An effort to create an open standard for transmitting metrics at scale, with support for both [text representation](/docs/text-format) and [Protocol Buffers](/docs/protobuf-format).
  favicon: /images/logo/logo.png

  assets:
    js:
    - jquery-3.3.1.min
    - app
